# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis
language: r
sudo: required
warnings_are_errors: false

apt_packages:
          - r-cran-rjava

env:
  global:
    - CRAN: http://cran.rstudio.com

r_packages:
  - covr

after_success:
  - Rscript -e 'covr::codecov()'
